swagger: "2.0"

info:
  title: Expense Tracker API
  description: Expense tracker backend is a backend service where any individual can join into the system and very easily with minimum effort can manage, monitor his day to life expenses.

  version: 1.0.0

schemes:
  - http
  - https

produces:
  - application/json

consumes:
  - application/json

basePath: "/api"

securityDefinitions:
  client_key:
    type: apiKey
    name: X-Client-key
    in: header

  api_token:
    type: apiKey
    name: Authorization
    in: header

tags:
  - name: User
    description: API's for user module.

  - name: Address
    description: API's for address module.

  - name: Expense Category
    description: API's for expense category module.

#############################################################################################################
#                                      # User #
#############################################################################################################
paths:
  /:
    get:
      summary: "Expense tracker test API"
      description: "Test API for expense tracker"
      tags:
        - User
      consumes:
        - application/json
      responses:
        "200":
          description: "Response after successful api call into the system"
          schema:
            $ref: "#/definitions/Success"

  /user/registration:
    post:
      summary: "User registration"
      description: "User registration into the system with email & password"
      tags:
        - User
      consumes:
        - application/json
      parameters:
        - name: item
          in: body
          required: true
          description: "Set request parameter to registration into the system"
          schema:
            $ref: "#/definitions/RegistrationObject"
      responses:
        "200":
          description: "Response after successful registration into the system"
          schema:
            $ref: "#/definitions/Success"

  /user/login:
    post:
      summary: "User login"
      description: "User log into the system with email & password"
      tags:
        - User
      consumes:
        - application/json
      security:
      # - client_key: []
      # - api_token: []
      parameters:
        - name: item
          in: body
          required: true
          description: "Set request parameter to log into the system"
          schema:
            $ref: "#/definitions/LoginObject"
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/LoginResponse"

  /user/verify-via-otp:
    post:
      summary: "User verification"
      description: "User verification via otp"
      tags:
        - User
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: item
          in: body
          required: true
          description: "Set request parameter to user verify"
          schema:
            $ref: "#/definitions/UserVerificationObject"
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/Success"

  /user/forgot-password:
    post:
      summary: "User forgot password"
      description: "User will change password due to forgot password"
      tags:
        - User
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: item
          in: body
          required: true
          description: "Set request parameter to update password"
          schema:
            $ref: "#/definitions/ForgotPasswordObject"
      responses:
        "200":
          description: "Response after successful password update due to forgot password"
          schema:
            $ref: "#/definitions/Success"

  /user/change-password:
    post:
      summary: "User change password"
      description: "User will change password"
      tags:
        - User
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: item
          in: body
          required: true
          description: "Set request parameter to change password"
          schema:
            $ref: "#/definitions/PasswordChangeObject"
      responses:
        "200":
          description: "Response after successful password change"
          schema:
            $ref: "#/definitions/Success"

  /user/update-profile/{userId}:
    patch:
      summary: "User profile update"
      description: "User will update his profile"
      tags:
        - User
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: item
          in: body
          required: true
          description: "Set request parameter to update user profile"
          schema:
            $ref: "#/definitions/UserProfileUpdateObject"
      responses:
        "200":
          description: "Response after successful user profile update"
          schema:
            $ref: "#/definitions/Success"

  /user/{userId}:
    get:
      summary: "Get user information"
      description: "Get any specific user information by user id"
      tags:
        - User
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: "Response containing user information"
          schema:
            $ref: "#/definitions/UserInformationResponse"

    delete:
      summary: "Deactivate user account"
      description: "Deactivate any specific user account by user id"
      tags:
        - User
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: "Response after successfully deactivating user account"
          schema:
            $ref: "#/definitions/Success"


############################################################################################################
#                                     # Address #
############################################################################################################
  /user/{userId}/addresses:
    get:
      summary: "User addresses"
      description: "Get user wise addresses"
      tags:
        - Address
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: "Response after successfully getting user addresses"
          schema:
            $ref: "#/definitions/AddressResponse"

    post:
      summary: "Add user addresses"
      description: "Add user wise addresses"
      tags:
        - Address
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: item
          in: body
          required: true
          description: "Set request parameter to add user address"
          schema:
            $ref: "#/definitions/AddUserAddressObject"
      responses:
        "200":
          description: "Success response after successfully adding user addresses"
          schema:
            $ref: "#/definitions/Success"

  /user/{userId}/addresses/{addressId}:
    get:
      summary: "Get user wise a specific address"
      description: "Get user wise a specific address"
      tags:
        - Address
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: addressId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: "Response after successfully getting user wise a specific address"
          schema:
            $ref: "#/definitions/AddressObject"

    patch:
      summary: "Update user wise a specific address"
      description: "Update user wise a specific address"
      tags:
        - Address
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: addressId
          in: path
          required: true
          type: string
        - name: item
          in: body
          required: true
          description: "Set request parameter to update user address"
          schema:
            $ref: "#/definitions/UpdateUserAddressObject"
      responses:
        "200":
          description: "Response after successfully updating user wise a specific address"
          schema:
            $ref: "#/definitions/Success"

    delete:
      summary: "Delete user wise a specific address"
      description: "Delete user wise a specific address"
      tags:
        - Address
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: addressId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: "Response after successfully deleting user wise a specific address"
          schema:
            $ref: "#/definitions/Success"


#############################################################################################################
#                                     # Expense Category #
#############################################################################################################
  /user/{userId}/expense-categories:
    get:
      summary: "User expense categories"
      description: "Get user wise expense categories"
      tags:
        - Expense Category
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: "Response after successfully getting user expense categories"
          schema:
            $ref: "#/definitions/ExpenseCategoriesResponse"

    post:
      summary: "User expense categories"
      description: "Add user wise expense categories"
      tags:
        - Expense Category
      consumes:
        - application/json
      security:
        - api_token: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: item
          in: body
          required: true
          description: "Set request parameter to add user expense category"
          schema:
            $ref: "#/definitions/AddUserExpenseCategoryObject"
      responses:
        "200":
          description: "Response after successfully adding user expense category"
          schema:
            $ref: "#/definitions/Success"

##############################################################################################################                                                                                                         #
#                                     # Definitions #                                                                                                                                                                                                      #
##############################################################################################################
definitions:
  Success:
    type: object
    description: "Success"
    properties:
      statusCode:
        type: integer
        example: 200
      status:
        type: string
        example: "success"
      message:
        type: string
        example: "Success message"

  RegistrationObject:
    type: object
    description: "Login Object"
    required:
      - email
      - password
    properties:
      email:
        type: string
        example: "example@example.com"
      password:
        type: string
        example: "password"

  LoginObject:
    type: object
    description: "Login Object"
    required:
      - email
      - password
      - isRemember
    properties:
      email:
        type: string
        example: "example@example.com"
      password:
        type: string
        example: "password"
      isRemember:
        type: boolean
        default: false

  LoginResponse:
    type: object
    description: "Login Response"
    properties:
      id:
        type: string
        example: "652fcc372b2f01d93d472ccb"
      firstName:
        type: string
        example: "firstName"
      email:
        type: string
        example: "example@example.com"
      isRemember:
        type: boolean
        default: false
      token:
        type: string
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.............."
      tokenExpiresAt:
        type: string
        example: "2023-10-18 07:17:01 PM"

  UserVerificationObject:
    type: object
    description: "User Verification Object"
    required:
      - otp
    properties:
      otp:
        type: string
        example: "1234"

  ForgotPasswordObject:
    type: object
    description: "Forgot Password Object"
    required:
      - newPassword
    properties:
      newPassword:
        type: string
        example: "password"

  PasswordChangeObject:
    type: object
    description: "Password Change Object"
    required:
      - oldPassword
      - newPassword
    properties:
      oldPassword:
        type: string
        example: "oldPassword"
      newPassword:
        type: string
        example: "newPassword"

  UserProfileUpdateObject:
    type: object
    description: User Profile Update Object
    properties:
      firstName:
        type: string
        example: "first name"
      lastName:
        type: string
        example: "last name"
      userName:
        type: string
        example: "user name"
      dob:
        type: string
        example: "14-02-1997"
      gender:
        type: string
        default: "Male"

  UserInformationResponse:
    type: object
    description: User Information Response
    properties:
      firstName:
        type: string
        example: "first name"
      lastName:
        type: string
        example: "last name"
      userName:
        type: string
        example: "user name"
      dob:
        type: string
        example: "14-02-1997"
      gender:
        type: string
        default: "Male"
      email:
        type: string
        example: "example@example.com"
      addresses:
        type: array
        items:
          $ref: "#/definitions/AddressObject"

  AddressObject:
    type: object
    description: "Address Response"
    properties:
      address:
        type: string
        example: "address"
      country:
        type: string
        example: "country"
      city:
        type: string
        example: "city"
      state:
        type: string
        example: "state"
      postalCode:
        type: string
        example: "5840"
      isActive:
        type: boolean
        default: true
      createdAt:
        type: string
        example: "2023-10-18 07:17:01 PM"

  AddressResponse:
    type: object
    description: "Address Object"
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/AddressObject"

  AddUserAddressObject:
    type: object
    description: "AddUser Address Object"
    required:
      - address
      - country
      - city
      - postalCode
    properties:
      address:
        type: string
        example: "address"
      country:
        type: string
        example: "country"
      city:
        type: string
        example: "city"
      state:
        type: string
        example: "state"
      postalCode:
        type: string
        example: "5840"

  UpdateUserAddressObject:
    type: object
    description: "Update UserAddress Object"
    properties:
      address:
        type: string
        example: "address"
      country:
        type: string
        example: "country"
      city:
        type: string
        example: "city"
      state:
        type: string
        example: "state"
      postalCode:
        type: string
        example: "5840"
      isActive:
        type: boolean
        default: true

  ExpenseCategoriesResponse:
    type: object
    description: "Expense Categories Response"
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/ExpenseCategoriesObject"

  ExpenseCategoriesObject:
    type: object
    description: "Expense Categories Object"
    properties:
      id:
        type: string
        example: "6393bcjbdknjdvn....."
      categoryName:
        type: string
        example: "Rent"
      categoryDescription:
        type: string
        example: "Description of expense category"
      isActive:
        type: boolean
        default: true
      createdAt:
        type: string
        format: date-time

  AddUserExpenseCategoryObject:
    type: object
    description: "AddUser Expense Category Object"
    properties:
      categoryName:
        type: string
        example: "Rent"
      categoryDescription:
        type: string
        example: "Description of expense category"
